# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment: HeadofSecurityJumpsuit

- type: startingGear
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment: HeadofSecurityJumpskirt

- type: startingGear
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment: HeadofSecurityTurtleneck

- type: startingGear
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment: HeadofSecurityTurtleneckSkirt

- type: startingGear
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment: HeadofSecurityFormalSuit

- type: startingGear
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment: HeadofSecurityFormalSkirt

- type: startingGear
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal
    
- type: loadout
  id: HeadofSecurityJumpsuitBlue
  equipment: HeadofSecurityJumpsuitBlue
  
- type: startingGear
  id: HeadofSecurityJumpsuitBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlue
    
- type: loadout
  id: HeadofSecurityParadeSuit
  equipment: HeadofSecurityParadeSuit
  
- type: startingGear
  id: HeadofSecurityParadeSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSParadeMale
    
- type: loadout
  id: HeadofSecurityParadeSkirt
  equipment: HeadofSecurityParadeSkirt
  
- type: startingGear
  id: HeadofSecurityParadeSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSParadeMale

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment: HeadofSecurityHead

- type: startingGear
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoscap
    
- type: loadout
  id: HeadofSecurityHat
  equipment: HeadofSecurityHat
    
- type: startingGear
  id: HeadofSecurityHat
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment: HeadofSecurityBeret

- type: startingGear
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment: HeadofSecurityCloak

- type: startingGear
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment: HeadofSecurityMantle

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment: HeadofSecurityCoat

- type: startingGear
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment: HeadofSecurityWinterCoat

- type: startingGear
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS